/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package searchtool;

import java.util.List;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        List<Branch> branches = loadBranchData();
        BranchSearcher branchSearcher = new BranchSearcher(branches);
        Scanner scanner = new Scanner(System.in);
        try {
            String searchBy = null;
            while (!"exit".equalsIgnoreCase(searchBy)) {
                System.out.println("Please enter your search criteria, Accepted Zip code, State, City, Type, Bank Name or City & State:");
                searchBy = scanner.nextLine();
                System.out.printf("User input: %s%n", searchBy);
                List<Branch> matchingBranches = branchSearcher.searchBranch(searchBy);
                matchingBranches.forEach(System.out::println);
            }
        } catch(Exception e) {
            e.printStackTrace();
            // System.in has been closed
            System.err.println("System.in was closed; exiting");
        }
    }

    private static List<Branch> loadBranchData() {
        return new BranchCsvLoader().loadData();
    }
}
